### ISSUE TITLE
sunrise am/pm using sunset 

### ISSUE THREAD

**Issue by MikeIsHereWorking** [madzadev/weather-app#2]
I don't know how to do a pull request on a repo that is not mine
on line 49 of Metrics.jsx
unit={getAMPM(systemUsed, data.sys.sunset, data.timezone)}
should be 
unit={getAMPM(systemUsed, data.sys.sunrise, data.timezone)}

**Comment by madzadev** [comment]
Thanks a lot for looking into the codebase and contributing! 😉
I've fixed the line you noted! On how to make a pull request, you can check out the [docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) 📃
